### ISSUE TITLE
installation: pinning Flask-WTF to 0.13.1?

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-oauth2server#105]
Before, this package required `'Flask-WTF>=0.13'`. In 4bed9bda6dfa8727066fad59a1869f414a725996, this was changed to `'Flask-WTF==0.13.1'`.  This change "broke" the CERN Analysis Preservation overlay... Is there any particular reason why invenio-oauth2server would require this concrete Flask-WTF version?

**Comment by lnielsen** [comment]
Ping @PaulinaLach @slint @krzysztof

**Comment by slint** [comment]
`Flask-WTF >= 0.14` seemed to be completely breaking `WTForms-Alchemy` (_I'm trying to find the broken build in Travis atm_). I think the more appropriate fix would be to specify `Flask-WTF < 0.14` and investigate further if there is a need for a patch on either of the two involved libraries.
