### ISSUE TITLE
tests: check oauth2 authorisation flow templates

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauth2server#124]
Go through an OAuth authorisation flow with Invenio and check the templates to see if they make sense and are correctly rendered.

Manual test:
- Create a developer application
- Test authorisation flow
- Figure out what is actually returned in access token response (e.g. is email returned)
- Compare with other services.

**Comment by lnielsen** [comment]
I think I can close this issue right?

**Comment by hjhsalo** [comment]
Sure
