### ISSUE TITLE
Set-Cookie in response headers

### ISSUE THREAD

**Issue by dinosk** [inveniosoftware/invenio-oauth2server#127]
The tests in test_decorators.py currently fail for the devel branch, after the last commit in invenio-accounts, making sessions permanent.
Specifically, all these [asserts](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/tests/test_decorators.py#L46) checking if the Set-Cookie is in the headers are failing, even though the status codes are returned correctly.

**Comment by lnielsen** [comment]
@dinosk Will you look into how to fix it?

**Comment by lnielsen** [comment]
Fixed by inveniosoftware/invenio-accounts#236
