### ISSUE TITLE
tests: check that no refresh token is associated with personal access token

### ISSUE THREAD

**Issue by hjhsalo** [inveniosoftware/invenio-oauth2server#138]
When authorization token is returned to a client after a successful 'Authorization Code Grant' -flow the response sent by invenio-oauth2server contains also a refresh token. (https://github.com/inveniosoftware/invenio-oauth2server/issues/137)

Manually test and report if refresh token is generated when user creates a personal access token. Note that refresh token should NOT be created.

**Comment by lnielsen** [comment]
Confirmed that personal access tokens do **not** have refresh tokens.
