### ISSUE TITLE
ui: clarify who is the logged in user and who is the author of application in authorization request form

### ISSUE THREAD

**Issue by hjhsalo** [inveniosoftware/invenio-oauth2server#140]
Currently authorization request form might not highlight enough who is the logged in user / identity, i.e. whose resources the application is requesting authorization.

Possibly the application name and author of application should also be highlighted more. 

Current invenio-oauth2server authorization request form looks like this:

![authorization_request_form](https://user-images.githubusercontent.com/9445833/29087710-140969d8-7c77-11e7-94fe-d76990bfea3a.png)

For inspiration, here is how GitHub and Google have done their OAuth application authorization request forms:

![authorization_request_form_google](https://user-images.githubusercontent.com/9445833/29087712-17b3079c-7c77-11e7-9563-9c789b5e0483.png)

![authorization_request_form_github](https://user-images.githubusercontent.com/9445833/29087711-16b545f8-7c77-11e7-8b45-a18e7cc50655.png)

**Comment by switowski** [comment]
@hjhsalo @lnielsen - what do you guys think about this (adding @drjova for the UI touch :smile: ):

![oauth2](https://user-images.githubusercontent.com/4835412/29132094-50ed4c12-7d2f-11e7-8784-762566ec54d6.png)

`More info` link is only displayed if the user filled in the description of the application (I would like to add the arrow to indicates that it's an accordion, not an external link, but I don't want to add custom CSS and Bootstrap3 doesn't support icons for accordions by default).

Also, how can I add some permissions to my custom application? I don't see any option when I'm creating the application.

**Comment by switowski** [comment]
Latest screenshots are here: https://github.com/inveniosoftware/invenio-oauth2server/pull/151
