### ISSUE TITLE
form: Token Form does not validate name length

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-oauth2server#168]
The [TokenForm](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/forms.py#L167), is not validating its `name` field for the maximum length of 40 characters, [as defined in the model](https://github.com/inveniosoftware/invenio-oauth2server/blob/0411429f530c941c2154163821915c04a0cb050d/invenio_oauth2server/models.py#L136).

#### Solutions

- Using the `model_form_factory` as in the [other forms](https://github.com/inveniosoftware/invenio-oauth2server/blob/0411429f530c941c2154163821915c04a0cb050d/invenio_oauth2server/forms.py#L119)
- Using the [WTForms Length validator](http://wtforms.simplecodes.com/docs/0.6/validators.html#wtforms.validators.Length)

**Comment by lnielsen** [comment]
Probably fastest is to go with Lenght validator?
