### ISSUE TITLE
tests: build error 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauth2server#181]
https://travis-ci.org/inveniosoftware/invenio-oauth2server/jobs/378447598

**Comment by slint** [comment]
Apparently, Flask docs for v0.11 are [no longer there](http://flask.pocoo.org/docs/0.11). Docs for [v0.12 are good though](http://flask.pocoo.org/docs/0.12/)... So updating the docs' [`conf.py`](https://github.com/inveniosoftware/invenio-oauth2server/blob/b00ac38f95577855ff08a852aeee6ada8b290ac4/docs/conf.py#L322) should be enough to fix the build.

The question is, do we also update [the `setup.py` dependency](https://github.com/inveniosoftware/invenio-oauth2server/blob/b00ac38f95577855ff08a852aeee6ada8b290ac4/setup.py#L72) as well? Doing so might possibly break other invenio packages that depend on `invenio-oauth2server` and have a minimum version of 0.11.1, causing a conflict with this module... 

This though is probably related to the bigger issue of syncing common dependencies (i.e. `flask`, `six`, `wtforms`, etc) between all invenio modules. Also, Flask 1.0 is out, so maybe it makes sense to plan an upgrade campaign at some point and address these issues then...
