### ISSUE TITLE
global: fix import error

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-oauth2server#196]
Same as:
* [pytest-invenio #42](https://github.com/inveniosoftware/pytest-invenio/issues/42)
* [invenio-oauth2server #196](https://github.com/inveniosoftware/invenio-oauth2server/issues/196)

https://travis-ci.org/inveniosoftware/invenio-oauth2server/jobs/656679343
```
Warning, treated as error:
autodoc: failed to import module u'ext' from module u'invenio_oauth2server'; the following exception was raised:
cannot import name cached_property
The command "./run-tests.sh" exited with 2.
```

Fix also deprecation warning in Travis config:
https://travis-ci.org/inveniosoftware/invenio-oauth2server/jobs/656679343/config

**Comment by kprzerwa** [comment]
currently cannot upgrade flash_oauthlib to support werkzeug, as the module is deprecated
