### ISSUE TITLE
global: release v1.3.0

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauth2server#214]
Depends on:

- #222 
- ~~#213~~
- ~~#194~~
- ~~#215~~

https://invenio.readthedocs.io/en/master/community/contributing/maintainers-guide/releasing.html#module-release

**Comment by ppanero** [comment]
This is dependent on 3 issues, but one of them, #194, has only been set as a "nice to have" in the sprint. Shall it be moved to TODO? Or can the release go ahead anyway?
