### ISSUE TITLE
oauth2server: end-user documentation 

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-oauth2server#52]
TOC:
- Features
- Overview
   - Understanding API Authentication in Invenio
     - Session (Secure HTTP only cookie) + CSRF token (JWT) usually a browser
        - ``Cookie: ...`` + ``Authorization: Bearer <CSRF token>``
     - Access token usually a machine (TODO: what about implicit grant - would need a CSRF token as well).
        - ``Authorization: Bearer <token>`` or ``?access_token=<token>``
   - Obtaining a session and CSRF token
      - Login (Invenio-Accounts) to obtain a session 
      - CSRF token - use Jinja context processor ``{{ jwt() }}`` or ``{{jwt_token()}}``) to embed CSRF token in DOM tree.  (this should probably be added by default to Search-UI)
   - Obtaining an access token
       - Personal access token (API key)
       - OAuth 2.0 Flows: (see nice [doc](https://auth0.com/docs/api-auth/which-oauth-flow-to-use) from Auth0)
          - Actors: Client, Resource Owner, Resource Server
          - Client credentials grant (client is also resource owner)
          - Authorization code grant (client is a web app on a server or a native application)
          - Implicit grant (Single Page Application - JavaScript)
          - Password grant (disabled by default)
       - Authorization Code Grant
       - Client credentials grant
       - Implicit grant:
          - TODO: check life time of tokens, and confidential vs public clients. Understand security implications for SPAs (e.g implicit tokens must not be refreshable).
       - Refreshing an access token   
   - Security considerations: Cross-Origin Resource Sharing (CORS) considerations
- Usage:
   - Protecting your REST API with authentication
     - Register blueprints on API application.  By default, the API application has a [``before_request``](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/ext.py#L181) that will check an access token if is used and ``current_user`` 
     - If you want to require authentication use ``@require_api_auth()`` (similar to ``@login_required`` in the UI). 
   - Delegating rights via scopes
     - ``@require_oauth_scopes()``
   - Registering a client
  

@lnielsen commented on [Mon Aug 18 2014](https://github.com/inveniosoftware/invenio/issues/2115)
- [ ] OAuth 2.0 Overview 
- [ ] Normal flow
- [ ] JavaScript flow
- [ ] Native app flow
- [x] Endpoint documentation
- [ ] Integrate with REST API docuemntation

**Comment by krzysztof** [comment]
The documentation should go to Usage section (i.e. docstring in ``invenio_oauth2server/__init__.py``)
