### ISSUE TITLE
config: clean from not used somewhere?

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-oauth2server#71]
I try to search and I didn't found a real usage for this variable:

- OAUTH2SERVER_ALLOWED_GRANT_TYPES
- OAUTH2SERVER_ALLOWED_RESPONSE_TYPES
- OAUTH2_PROVIDER_ERROR_ENDPOINT

Do you think we should leave them?

-----------------------------------------------------
cc @jirikuncar @lnielsen

**Comment by lnielsen** [comment]
They are all there for a very reason:
- https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/models.py#L201-L209 (methods are being called from Flask-OAuthlib
- https://github.com/lepture/flask-oauthlib/blob/e1bb478b2015239dd12f1d3ee13fb2627a5a3407/flask_oauthlib/provider/oauth2.py#L101

**Comment by jirikuncar** [comment]
@hachreak just make sure that they are documented.
