### ISSUE TITLE
provider: get_user function

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-oauth2server#72]
Is still useful the [get_user](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/provider.py#L41) function?
Because it's filtering the users by `username`, but, actually, it doesn't exist anymore (moved to `userprofiles`).
It should be updated or removed?

---

cc @jirikuncar @lnielsen

**Comment by lnielsen** [comment]
The easiest is to fix it to use the invenio_accounts User model, and query by email address instead (which is also what we require in our login forms). If we remove it, you have to add a check to make sure people don't specify password grant type in https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/config.py#L45

**Comment by jirikuncar** [comment]
+1 for changing `username` to `email`
