### ISSUE TITLE
global: flask-oauthlib prevents reading the request stream

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauth2server#73]
For every API request we call [``verify_oauth_token_and_set_current_user``](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/ext.py#L129). This method calls Flask-Oauthlib which makes a call to [``request.form.to_dict()``](https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/utils.py#L31)

Accessing ``request.form`` makes Werkzeug parse the request body, and thereby preventing e.g. Invenio-Files-REST to read the request body via ``request.stream``, which is needed for fast file uploads.

**Comment by jirikuncar** [comment]
@lnielsen I don't see a way around it unless mock the `request.stream` or perform the authentication after copying the file. Can you point us to the code in Invenio-Files-REST that relies on `request.stream`?

**Comment by lnielsen** [comment]
[Here](https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/views.py#L104)

It's crucial to be able to read from ``request.stream`` in Files-REST in order to have high performance. Uploading files via ``application/multipart-formdata`` (i.e. reading stuff from ``request.form`` and ``request.files``) kills performance because it writes data to disk in temporary files (Werkzeug for files >500kb) and spends time parsing the form data.

I will try to see if I can mock the ``request.stream`` or ``request.form`` to prevent Flask-Oauthlib from reading the request.body.

**Comment by lnielsen** [comment]
Actually, digging a bit deeper into it, I think the problem is different.

Werkzeug's form data parser [kicks-in](https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py#L355) if the Content-Type header is set. The form parser [first checks](https://github.com/pallets/werkzeug/blob/master/werkzeug/formparser.py#L184-L187) if Content-Length exceeds maximum allowed length, then try to [find a suitable parser function](https://github.com/pallets/werkzeug/blob/master/werkzeug/formparser.py#L191) for a given MIME type. All this is executed when Flask-OAuthlib calls ``request.form.to_dict()``.

We have set ``MAX_CONTENT_LENGTH`` in Files-REST to ~15mb, since anything above 500kb will be written to a temporary file, this possible exhausting the local disk (i.e. it makes sense to put a limit). However, in Files-REST we also want to allow very large file uploads in a single request via streaming the file in the body (and reading it from ``request.stream`` without writing it to temporary file on disk). 

If Werkzeug's form parser reversed the order to 1) find suitable parser for MIME type, then 2) check content length, then calls to ``request.form`` (like the one from Flask-OAuthlib) wouldn't be an issue, because Werkzeug wouldn't even try to read the data. I.e. change [this](https://github.com/pallets/werkzeug/blob/master/werkzeug/formparser.py#L173-L200), into something like this:

```python
def parse(self, stream, mimetype, content_length, options=None):
    if options is None:
        options = {}

    parse_func = self.get_parse_func(mimetype, options)
    if parse_func is not None:
        if self.max_content_length is not None and \
           content_length is not None and \
           content_length > self.max_content_length:
            raise exceptions.RequestEntityTooLarge()
        
        try:
            return parse_func(self, stream, mimetype,
                              content_length, options)
        except ValueError:
            if not self.silent:
                raise

    return stream, self.cls(), self.cls()
```

**Comment by lnielsen** [comment]
I think these two PRs are the cleanest way of fixing the issue:
- inveniosoftware/invenio-base#94 (allow custom Flask application class)
- inveniosoftware/invenio-files-rest#108 (custom Flask application class with a fixed form parser)

This can easily be used only on the API application like this:

```python
from invenio_files_rest.app import Flask

create_api = create_app_factory(
    'myapp',
    ....
    app_class=Flask,
)
```
