### ISSUE TITLE
installation: incompatibility with oauthlib v2.0.0

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-oauth2server#78]
**Problem**:
 oauthlib v2.0.0 released 10 days ago (previous version was 1.1.2).
There is some incompatibility with latest version of `oauthlib` and current stable version of `flask-oauthlib` (0.9.3). 

see here: https://travis-ci.org/hachreak/invenio-oauth2server/builds/159590104
A issue already opened: https://github.com/lepture/flask-oauthlib/issues/296

**Proposal**
The easy solution for now is to pin (again) the version and investigate why it doesn't work.

**Comment by jirikuncar** [comment]
Hopefully the fix will be soon in upstream: https://github.com/idan/oauthlib/pull/437

**Comment by thedrow** [comment]
I have released 2.0.1 which fixes the problem.

**Comment by jirikuncar** [comment]
@thedrow thanks for an update 👍
